spring:
  application:
    name: chat-app
  datasource:
        url: jdbc:postgresql://localhost:5432/chatapp
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
  jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        open-in-view: false
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
security:
  jwt:
    secret: a+mn3JdYxP2wsBITgnpIOA9zEag8EUPE022WDSwDcpPzvgdWGXb6hbskhyKK6wY1
    issuer: chat-app
    accessTokenExpirationInSeconds: 900       # 15 dk
    refreshTokenExpirationInSeconds: 604800   # 7 gün

encryption:
  aes-key: K7pZnQ2mXvR8sLdYwT4cHjFbNgUeAiOq3V6WkE9GyM0=

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
